# Generated by Django 4.2.1 on 2023-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=255)),
                ('yellow', models.CharField(max_length=255)),
                ('green', models.CharField(max_length=255)),
            ],
        ),
    ]
