# Generated by Django 4.2.1 on 2023-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='green',
            field=models.DecimalField(decimal_places=25, max_digits=25),
        ),
        migrations.AlterField(
            model_name='color',
            name='red',
            field=models.DecimalField(decimal_places=25, max_digits=25),
        ),
        migrations.AlterField(
            model_name='color',
            name='yellow',
            field=models.DecimalField(decimal_places=25, max_digits=25),
        ),
    ]
