# Generated by Django 4.2.1 on 2023-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_color_green_alter_color_red_alter_color_yellow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='green',
            field=models.IntegerField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='color',
            name='red',
            field=models.IntegerField(max_length=6000),
        ),
        migrations.AlterField(
            model_name='color',
            name='yellow',
            field=models.IntegerField(max_length=6000),
        ),
    ]
